# Generated by Django 5.2.10 on 2026-01-20 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField(default=1)),
                ('title', models.CharField(default='Untitled Document', max_length=255)),
                ('schema_version', models.IntegerField(default=1)),
                ('content_json', models.JSONField(blank=True, default=dict)),
                ('content_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('docx', 'DOCX'), ('pdf', 'PDF'), ('json', 'JSON')], max_length=10)),
                ('file', models.FileField(upload_to='doc_builder/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='doc_builder.documentproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
