# Generated by Django 5.2 on 2026-04-26 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_builder', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentFile',
        ),
        migrations.DeleteModel(
            name='DocumentProject',
        ),
    ]
