# Generated by Django 5.2 on 2026-04-03 14:03

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_historicaldevicecomponent_historicaldevicerza_and_more'),
        ('directory', '0005_historicalcity_historicalcontact_historicalcountry_and_more'),
        ('orders', '0010_alter_contract_contract_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Номер КП')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлено'), ('accepted', 'Принято'), ('rejected', 'Отклонено'), ('expired', 'Истекло')], default='draft', max_length=20, verbose_name='Статус')),
                ('date', models.DateField(verbose_name='Дата КП')),
                ('valid_days', models.PositiveIntegerField(default=30, verbose_name='Срок действия (дней)')),
                ('valid_until', models.DateField(blank=True, help_text='Вычисляется автоматически: дата + срок действия', null=True, verbose_name='Действует до')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, verbose_name='Ставка НДС, %')),
                ('payment_terms', models.CharField(choices=[('50_50', '50% аванс, 50% перед отгрузкой'), ('100_post_7', '100% в течение 7 дней после отгрузки'), ('100_post_30', '100% в течение 30 дней после отгрузки'), ('custom', 'Произвольные условия')], default='50_50', max_length=20, verbose_name='Условия оплаты')),
                ('advance_percent', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5, verbose_name='Аванс, %')),
                ('pre_shipment_percent', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5, verbose_name='Перед отгрузкой, %')),
                ('post_payment_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Постоплата, %')),
                ('manufacturing_period', models.CharField(default='60-90', max_length=20, verbose_name='Срок изготовления')),
                ('warranty_months', models.PositiveIntegerField(default=60, verbose_name='Гарантия (мес.)')),
                ('delivery_included', models.BooleanField(default=False, verbose_name='Доставка включена')),
                ('delivery_city', models.CharField(blank=True, max_length=255, verbose_name='Город доставки')),
                ('additional_conditions', models.TextField(blank=True, help_text='МЭК, соответствие ТЗ и прочее. Если пусто — не выводится в КП.', verbose_name='Дополнительные условия')),
                ('is_template', models.BooleanField(default=False, help_text='Сохранить как типовое для участника запроса', verbose_name='Типовое КП')),
                ('based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_offers', to='specs.commercialoffer', verbose_name='На основании КП')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_offers', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_offers', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='orders.order', verbose_name='Заказ')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='orders.orderparticipant', verbose_name='Участник запроса')),
            ],
            options={
                'verbose_name': 'Коммерческое предложение',
                'verbose_name_plural': 'Коммерческие предложения',
                'ordering': ['-date', '-version'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCommercialOffer',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('offer_number', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Номер КП')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлено'), ('accepted', 'Принято'), ('rejected', 'Отклонено'), ('expired', 'Истекло')], default='draft', max_length=20, verbose_name='Статус')),
                ('date', models.DateField(verbose_name='Дата КП')),
                ('valid_days', models.PositiveIntegerField(default=30, verbose_name='Срок действия (дней)')),
                ('valid_until', models.DateField(blank=True, help_text='Вычисляется автоматически: дата + срок действия', null=True, verbose_name='Действует до')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, verbose_name='Ставка НДС, %')),
                ('payment_terms', models.CharField(choices=[('50_50', '50% аванс, 50% перед отгрузкой'), ('100_post_7', '100% в течение 7 дней после отгрузки'), ('100_post_30', '100% в течение 30 дней после отгрузки'), ('custom', 'Произвольные условия')], default='50_50', max_length=20, verbose_name='Условия оплаты')),
                ('advance_percent', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5, verbose_name='Аванс, %')),
                ('pre_shipment_percent', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5, verbose_name='Перед отгрузкой, %')),
                ('post_payment_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Постоплата, %')),
                ('manufacturing_period', models.CharField(default='60-90', max_length=20, verbose_name='Срок изготовления')),
                ('warranty_months', models.PositiveIntegerField(default=60, verbose_name='Гарантия (мес.)')),
                ('delivery_included', models.BooleanField(default=False, verbose_name='Доставка включена')),
                ('delivery_city', models.CharField(blank=True, max_length=255, verbose_name='Город доставки')),
                ('additional_conditions', models.TextField(blank=True, help_text='МЭК, соответствие ТЗ и прочее. Если пусто — не выводится в КП.', verbose_name='Дополнительные условия')),
                ('is_template', models.BooleanField(default=False, help_text='Сохранить как типовое для участника запроса', verbose_name='Типовое КП')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('based_on', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='specs.commercialoffer', verbose_name='На основании КП')),
                ('executor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.order', verbose_name='Заказ')),
                ('participant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.orderparticipant', verbose_name='Участник запроса')),
            ],
            options={
                'verbose_name': 'historical Коммерческое предложение',
                'verbose_name_plural': 'historical Коммерческие предложения',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSpecification',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Сумма без НДС')),
                ('total_amount_with_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Сумма с НДС')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='specs.commercialoffer', verbose_name='КП')),
            ],
            options={
                'verbose_name': 'historical Спецификация',
                'verbose_name_plural': 'historical Спецификации',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OfferWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included', models.BooleanField(default=False, verbose_name='Включено')),
                ('days', models.PositiveIntegerField(default=15, verbose_name='Кол-во дней')),
                ('specialists', models.PositiveIntegerField(default=1, verbose_name='Кол-во специалистов')),
                ('trips', models.PositiveIntegerField(default=1, verbose_name='Кол-во выездов')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='specs.commercialoffer', verbose_name='КП')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_work_items', to='directory.typeofwork', verbose_name='Вид работ')),
            ],
            options={
                'verbose_name': 'Работа в КП',
                'verbose_name_plural': 'Работы в КП',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной контакт')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_links', to='directory.contact', verbose_name='Контактное лицо')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_contacts', to='orders.orderparticipant', verbose_name='Участник запроса')),
            ],
            options={
                'verbose_name': 'Контакт участника',
                'verbose_name_plural': 'Контакты участников',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Сумма без НДС')),
                ('total_amount_with_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Сумма с НДС')),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='specs.commercialoffer', verbose_name='КП')),
            ],
            options={
                'verbose_name': 'Спецификация',
                'verbose_name_plural': 'Спецификации',
            },
        ),
        migrations.CreateModel(
            name='SpecificationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.PositiveIntegerField(default=0, verbose_name='№ п/п')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Цена за ед.')),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Итого')),
                ('delivery_date', models.DateField(blank=True, help_text='Если отличается от общего срока (для отдельных партий)', null=True, verbose_name='Срок поставки')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('device_rza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specification_lines', to='devices.devicerza', verbose_name='Устройство РЗА')),
                ('mod_rza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specification_lines', to='devices.modrza', verbose_name='Модификация')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specification_lines', to='devices.product', verbose_name='Продукт из каталога')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='specs.specification', verbose_name='Спецификация')),
            ],
            options={
                'verbose_name': 'Позиция спецификации',
                'verbose_name_plural': 'Позиции спецификации',
                'ordering': ['line_number'],
            },
        ),
        migrations.AddIndex(
            model_name='commercialoffer',
            index=models.Index(fields=['order', 'participant'], name='specs_comme_order_i_d6651c_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialoffer',
            index=models.Index(fields=['status'], name='specs_comme_status_b946fe_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialoffer',
            index=models.Index(fields=['manager'], name='specs_comme_manager_8e8ded_idx'),
        ),
        migrations.AddConstraint(
            model_name='offerworkitem',
            constraint=models.UniqueConstraint(fields=('offer', 'work_type'), name='unique_offer_work_type'),
        ),
        migrations.AddConstraint(
            model_name='participantcontact',
            constraint=models.UniqueConstraint(fields=('participant', 'contact'), name='unique_participant_contact'),
        ),
        migrations.AddIndex(
            model_name='specificationline',
            index=models.Index(fields=['specification', 'line_number'], name='specs_speci_specifi_2cddc4_idx'),
        ),
    ]
