# Generated by Django 5.2 on 2026-04-06 14:35

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_historicaldevicecomponent_historicaldevicerza_and_more'),
        ('specs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOfferCalculation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('default_overhead_percent', models.DecimalField(decimal_places=2, default=15, max_digits=5, verbose_name='НР по умолчанию, %')),
                ('default_project_coeff', models.DecimalField(decimal_places=4, default=1, max_digits=6, verbose_name='Проектный коэффициент по умолчанию')),
                ('default_discount_coeff', models.DecimalField(decimal_places=4, default=1, max_digits=6, verbose_name='Скидочный коэффициент по умолчанию')),
                ('note', models.TextField(blank=True, default='', verbose_name='Примечание')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='specs.commercialoffer', verbose_name='КП')),
            ],
            options={
                'verbose_name': 'historical Расчёт к КП',
                'verbose_name_plural': 'historical Расчёты к КП',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OfferCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_overhead_percent', models.DecimalField(decimal_places=2, default=15, max_digits=5, verbose_name='НР по умолчанию, %')),
                ('default_project_coeff', models.DecimalField(decimal_places=4, default=1, max_digits=6, verbose_name='Проектный коэффициент по умолчанию')),
                ('default_discount_coeff', models.DecimalField(decimal_places=4, default=1, max_digits=6, verbose_name='Скидочный коэффициент по умолчанию')),
                ('note', models.TextField(blank=True, default='', verbose_name='Примечание')),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculation', to='specs.commercialoffer', verbose_name='КП')),
            ],
            options={
                'verbose_name': 'Расчёт к КП',
                'verbose_name_plural': 'Расчёты к КП',
            },
        ),
        migrations.CreateModel(
            name='CalculationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.PositiveIntegerField(verbose_name='№ п/п')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Базовая цена')),
                ('overhead_type', models.CharField(choices=[('equipment', 'Оборудование (15%)'), ('purchased', 'Покупное (30%)'), ('nku', 'НКУ (30%)'), ('custom', 'Произвольный')], default='equipment', max_length=20, verbose_name='Тип НР')),
                ('overhead_percent', models.DecimalField(decimal_places=2, default=15, max_digits=5, verbose_name='НР, %')),
                ('price_with_overhead', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Цена с НР')),
                ('project_coeff', models.DecimalField(decimal_places=4, default=1, max_digits=6, verbose_name='Проектный К')),
                ('estimated_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Сметная цена')),
                ('discount_coeff', models.DecimalField(decimal_places=4, default=1, max_digits=6, verbose_name='Скидочный К')),
                ('discounted_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Цена со скидкой')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Итого (кол-во × цена со скидкой)')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Примечание')),
                ('device_rza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.devicerza', verbose_name='Устройство РЗА')),
                ('mod_rza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.modrza', verbose_name='Модификация')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.product', verbose_name='Продукт')),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='specs.offercalculation', verbose_name='Расчёт')),
            ],
            options={
                'verbose_name': 'Позиция расчёта',
                'verbose_name_plural': 'Позиции расчёта',
                'ordering': ['line_number'],
            },
        ),
    ]
