# Generated by Django 5.2 on 2026-04-06 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0002_offer_calculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationline',
            name='is_optional',
            field=models.BooleanField(default=False, verbose_name='Опция'),
        ),
        migrations.AddField(
            model_name='calculationline',
            name='option_type',
            field=models.CharField(choices=[('none', 'Основная позиция'), ('parameter', 'Параметр/функция'), ('delivery', 'Доставка'), ('work', 'Работа'), ('other', 'Прочее')], default='none', max_length=20, verbose_name='Тип опции'),
        ),
        migrations.AddField(
            model_name='calculationline',
            name='parent_line',
            field=models.ForeignKey(blank=True, help_text='Если pricing_mode=included, цена прибавляется к этой позиции', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='option_lines', to='specs.calculationline', verbose_name='Родительская позиция'),
        ),
        migrations.AddField(
            model_name='calculationline',
            name='pricing_mode',
            field=models.CharField(choices=[('separate', 'Отдельная строка'), ('included', 'Включено в стоимость')], default='separate', max_length=20, verbose_name='Режим ценообразования'),
        ),
    ]
