# Generated by Django 5.2 on 2026-04-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0003_calcline_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloffercalculation',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Стоимость доставки'),
        ),
        migrations.AddField(
            model_name='historicaloffercalculation',
            name='delivery_pricing_mode',
            field=models.CharField(choices=[('separate', 'Отдельная строка'), ('included', 'Включено в стоимость')], default='separate', max_length=20, verbose_name='Режим доставки'),
        ),
        migrations.AddField(
            model_name='offercalculation',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Стоимость доставки'),
        ),
        migrations.AddField(
            model_name='offercalculation',
            name='delivery_pricing_mode',
            field=models.CharField(choices=[('separate', 'Отдельная строка'), ('included', 'Включено в стоимость')], default='separate', max_length=20, verbose_name='Режим доставки'),
        ),
        migrations.AddField(
            model_name='offerworkitem',
            name='pricing_mode',
            field=models.CharField(choices=[('separate', 'Отдельная строка'), ('included', 'Включено в стоимость')], default='separate', max_length=20, verbose_name='Режим цены'),
        ),
        migrations.AddField(
            model_name='offerworkitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Цена за единицу'),
        ),
    ]
