# Generated by Django 5.2 on 2026-04-08 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0014_shipment_batch"),
        ("specs", "0004_calc_delivery_work_prices"),
    ]

    operations = [
        migrations.AddField(
            model_name="specificationline",
            name="shipment_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="specification_lines",
                to="orders.shipmentbatch",
                verbose_name="Партия отгрузки",
            ),
        ),
    ]
