# Generated by Django 5.2 on 2026-03-30 16:59

import apps.edo.registry.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_historicalletter_seq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalletter',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalletter',
            name='number',
            field=models.CharField(db_index=True, editable=False, max_length=20, verbose_name='Номер документа'),
        ),
        migrations.AlterField(
            model_name='historicalletter',
            name='seq',
            field=models.PositiveIntegerField(db_index=True, editable=False, null=True, verbose_name='Сквозной номер'),
        ),
        migrations.AlterField(
            model_name='historicalletterfile',
            name='file',
            field=models.TextField(max_length=100, validators=[apps.edo.registry.models.models._validate_file], verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='historicalletterfile',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
    ]
