# Generated by Django 5.2 on 2026-04-01 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_created', models.CharField(choices=[('bell', 'Только в приложении'), ('email', 'Только email'), ('all', 'Приложение + email'), ('none', 'Отключены')], default='bell', max_length=10, verbose_name='Новые заказы')),
                ('order_status_changed', models.CharField(choices=[('bell', 'Только в приложении'), ('email', 'Только email'), ('all', 'Приложение + email'), ('none', 'Отключены')], default='all', max_length=10, verbose_name='Изменение статуса заказа')),
                ('order_deadline', models.CharField(choices=[('bell', 'Только в приложении'), ('email', 'Только email'), ('all', 'Приложение + email'), ('none', 'Отключены')], default='all', max_length=10, verbose_name='Дедлайны и просрочки')),
                ('contract_payment', models.CharField(choices=[('bell', 'Только в приложении'), ('email', 'Только email'), ('all', 'Приложение + email'), ('none', 'Отключены')], default='bell', max_length=10, verbose_name='Оплата контрактов')),
                ('comments', models.CharField(choices=[('bell', 'Только в приложении'), ('email', 'Только email'), ('all', 'Приложение + email'), ('none', 'Отключены')], default='bell', max_length=10, verbose_name='Комментарии')),
                ('import_completed', models.CharField(choices=[('bell', 'Только в приложении'), ('email', 'Только email'), ('all', 'Приложение + email'), ('none', 'Отключены')], default='bell', max_length=10, verbose_name='Завершение импорта')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
            },
        ),
    ]
