# Generated by Django 5.2 on 2026-04-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_historicalcity_historicalcontact_historicalcountry_and_more'),
        ('users', '0004_add_devices_module_to_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='my_customers',
            field=models.ManyToManyField(blank=True, related_name='assigned_managers', to='directory.orgunit', verbose_name='Мои заказчики'),
        ),
    ]
