# Generated by Django 5.2 on 2026-04-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_my_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_department_head',
            field=models.BooleanField(default=False, help_text='Даёт доступ к панели руководителя для своего отдела', verbose_name='Руководитель отдела'),
        ),
    ]
