# Generated by Django 5.2 on 2026-04-21 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_orgunit_add_service_sector'),
        ('users', '0006_user_is_department_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='org_unit',
            field=models.ForeignKey(blank=True, help_text='Узел OrgUnit (сектор/отдел/служба/компания), в котором сотрудник работает', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='directory.orgunit', verbose_name='Подразделение'),
        ),
        migrations.AddField(
            model_name='user',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Если не задан — определяется автоматически по дереву org_unit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL, verbose_name='Непосредственный руководитель'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_department_head',
            field=models.BooleanField(default=False, help_text='Руководитель своего org_unit: сектора, отдела, службы или компании', verbose_name='Руководитель отдела'),
        ),
    ]
