# Generated by Django 5.2 on 2026-04-21 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_add_department_model'),
        ('users', '0006_user_is_department_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_unit',
            field=models.ForeignKey(blank=True, help_text="Юрлицо (OrgUnit с business_role='internal'), в котором сотрудник оформлен", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_employees', to='directory.orgunit', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='user',
            name='department_unit',
            field=models.ForeignKey(blank=True, help_text='Служба/отдел/сектор внутри company_unit. Пусто, если сотрудник прямо на уровне компании', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='directory.department', verbose_name='Подразделение'),
        ),
        migrations.AddField(
            model_name='user',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Явный override. Если не задан — определяется по дереву department_unit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL, verbose_name='Непосредственный руководитель'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_department_head',
            field=models.BooleanField(default=False, help_text='Руководитель своего department_unit (или company_unit, если сидит на уровне компании)', verbose_name='Руководитель отдела'),
        ),
    ]
