# Generated by Django 5.2 on 2026-04-26 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_backfill_company_and_department_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='substitute_from',
            field=models.DateField(blank=True, help_text='Дата начала отсутствия (включительно)', null=True, verbose_name='Замещение с'),
        ),
        migrations.AddField(
            model_name='user',
            name='substitute_until',
            field=models.DateField(blank=True, help_text='Дата окончания отсутствия (включительно)', null=True, verbose_name='Замещение до'),
        ),
        migrations.AddField(
            model_name='user',
            name='substitute_user',
            field=models.ForeignKey(blank=True, help_text='Кто принимает решения вместо меня в период отсутствия', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituted_for', to=settings.AUTH_USER_MODEL, verbose_name='Замещающий'),
        ),
    ]
