# Generated by Django 5.2 on 2026-04-30 17:00

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0012_orgunithead'),
        ('users', '0009_user_substitute_from_user_substitute_until_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAssignment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('position', models.CharField(blank=True, help_text='Текстовое название должности в этом назначении', max_length=150, verbose_name='Должность')),
                ('is_head', models.BooleanField(default=False, help_text='Руководитель этого department (или company, если department пуст)', verbose_name='Руководитель')),
                ('is_primary', models.BooleanField(default=False, help_text='Ровно одно у пользователя; используется как default-контекст', verbose_name='Основное место')),
                ('is_active', models.BooleanField(default=True, help_text='False = архивная запись (увольнение/перевод). Не удаляется, чтобы не ломать исторические ссылки из EDO-документов.', verbose_name='Активно')),
                ('from_date', models.DateField(blank=True, null=True, verbose_name='Действует с')),
                ('to_date', models.DateField(blank=True, null=True, verbose_name='Действует по')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, help_text="Юрлицо (OrgUnit с business_role='internal')", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='directory.orgunit', verbose_name='Компания')),
                ('department', models.ForeignKey(blank=True, db_constraint=False, help_text='Пусто — сотрудник на уровне компании (например, ген.директор)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='directory.department', verbose_name='Подразделение')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'historical Назначение',
                'verbose_name_plural': 'historical Назначения',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, help_text='Текстовое название должности в этом назначении', max_length=150, verbose_name='Должность')),
                ('is_head', models.BooleanField(default=False, help_text='Руководитель этого department (или company, если department пуст)', verbose_name='Руководитель')),
                ('is_primary', models.BooleanField(default=False, help_text='Ровно одно у пользователя; используется как default-контекст', verbose_name='Основное место')),
                ('is_active', models.BooleanField(default=True, help_text='False = архивная запись (увольнение/перевод). Не удаляется, чтобы не ломать исторические ссылки из EDO-документов.', verbose_name='Активно')),
                ('from_date', models.DateField(blank=True, null=True, verbose_name='Действует с')),
                ('to_date', models.DateField(blank=True, null=True, verbose_name='Действует по')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text="Юрлицо (OrgUnit с business_role='internal')", on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='directory.orgunit', verbose_name='Компания')),
                ('department', models.ForeignKey(blank=True, help_text='Пусто — сотрудник на уровне компании (например, ген.директор)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='directory.department', verbose_name='Подразделение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Назначение',
                'verbose_name_plural': 'Назначения',
                'ordering': ['user', '-is_primary', 'company__name', 'department__name'],
                'indexes': [models.Index(fields=['user', 'is_primary'], name='users_assig_user_id_746e20_idx'), models.Index(fields=['company'], name='users_assig_company_11df70_idx'), models.Index(fields=['department'], name='users_assig_departm_4f91a2_idx'), models.Index(fields=['is_head'], name='users_assig_is_head_aed1e7_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('user',), name='uniq_primary_assignment_per_user'), models.UniqueConstraint(condition=models.Q(('department__isnull', False)), fields=('user', 'company', 'department'), name='uniq_user_company_department'), models.UniqueConstraint(condition=models.Q(('department__isnull', True)), fields=('user', 'company'), name='uniq_user_company_no_department')],
            },
        ),
    ]
