# Generated by Django 5.2 on 2026-02-18 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("directory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorgunit",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicalpq",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="orgunit",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="org_units",
                to="directory.country",
                verbose_name="Страна",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="org_units",
            field=models.ManyToManyField(
                blank=True, related_name="contacts", to="directory.orgunit", verbose_name="Организации"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="city",
            unique_together={("name", "country")},
        ),
        migrations.AddIndex(
            model_name="orgunit",
            index=models.Index(fields=["name"], name="directory_o_name_5a4e11_idx"),
        ),
        migrations.AddIndex(
            model_name="orgunit",
            index=models.Index(fields=["business_role"], name="directory_o_busines_92a86c_idx"),
        ),
    ]
