# Generated by Django 5.2 on 2026-04-21 14:27

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("directory", "0009_contactemployment_address_auto_history"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalDepartment",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("path", models.CharField(db_index=True, max_length=255)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("full_name", models.CharField(blank=True, max_length=500, verbose_name="Полное название")),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("service", "Служба"),
                            ("department", "Отдел"),
                            ("sector", "Сектор"),
                            ("other", "Другое"),
                        ],
                        default="department",
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="OrgUnit с business_role='internal' — юрлицо, к которому относится подразделение",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="directory.orgunit",
                        verbose_name="Компания",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Подразделение",
                "verbose_name_plural": "historical Подразделения",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("full_name", models.CharField(blank=True, max_length=500, verbose_name="Полное название")),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("service", "Служба"),
                            ("department", "Отдел"),
                            ("sector", "Сектор"),
                            ("other", "Другое"),
                        ],
                        default="department",
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="OrgUnit с business_role='internal' — юрлицо, к которому относится подразделение",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="departments",
                        to="directory.orgunit",
                        verbose_name="Компания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подразделение",
                "verbose_name_plural": "Подразделения",
                "indexes": [
                    models.Index(fields=["name"], name="directory_d_name_13c843_idx"),
                    models.Index(fields=["company"], name="directory_d_company_a7c168_idx"),
                ],
            },
        ),
    ]
