# Generated by Django 5.2 on 2026-04-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_contactemployment_address_auto_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorgunit',
            name='unit_type',
            field=models.CharField(choices=[('company', 'Головная компания / Холдинг'), ('branch', 'Филиал / Дочерняя компания'), ('division', 'Производственное отделение'), ('service', 'Служба'), ('department', 'Отдел'), ('sector', 'Сектор'), ('site', 'Площадка'), ('other', 'Другое')], default='company', max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='unit_type',
            field=models.CharField(choices=[('company', 'Головная компания / Холдинг'), ('branch', 'Филиал / Дочерняя компания'), ('division', 'Производственное отделение'), ('service', 'Служба'), ('department', 'Отдел'), ('sector', 'Сектор'), ('site', 'Площадка'), ('other', 'Другое')], default='company', max_length=20, verbose_name='Тип'),
        ),
    ]
