# Generated by Django 5.2.10 on 2026-01-20 10:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('template_type', models.CharField(choices=[('HTML', 'HTML'), ('DOCX', 'DOCX'), ('PDF', 'PDF')], max_length=10)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('RESTRICTED', 'Restricted')], default='PUBLIC', max_length=20)),
                ('owner_id', models.IntegerField(default=1)),
                ('allowed_users', models.JSONField(blank=True, default=list)),
                ('html_content', models.TextField(blank=True, default='')),
                ('editor_content', models.JSONField(blank=True, default=list)),
                ('docx_file', models.FileField(blank=True, null=True, upload_to='docx_templates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('ttl_days', models.IntegerField(default=7)),
                ('max_uses', models.IntegerField(default=50)),
                ('current_uses', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='templates_app.template')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('html_content', models.TextField(blank=True, default='')),
                ('editor_content', models.JSONField(blank=True, default=list)),
                ('docx_file', models.FileField(blank=True, null=True, upload_to='docx_versions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='templates_app.template')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('template', 'version_number')},
            },
        ),
    ]
