# Generated by Django 5.2 on 2026-03-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
