# Generated by Django 5.2 on 2026-02-18 13:54

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contract_number", models.CharField(max_length=100, unique=True, verbose_name="Номер контракта")),
                ("contract_date", models.DateField(blank=True, null=True, verbose_name="Дата контракта")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_paid", "Не оплачен"),
                            ("advance_paid", "Аванс оплачен"),
                            ("intermediate", "Промежуточная оплата"),
                            ("fully_paid", "Полностью оплачен"),
                        ],
                        default="not_paid",
                        max_length=20,
                        verbose_name="Статус оплаты",
                    ),
                ),
                (
                    "advance_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name="Аванс %"),
                ),
                (
                    "intermediate_percent",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="Промежуточная оплата %"
                    ),
                ),
                (
                    "post_payment_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name="Постоплата %"),
                ),
                (
                    "amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name="Сумма"),
                ),
                ("deadline_days", models.PositiveIntegerField(blank=True, null=True, verbose_name="Срок (дней)")),
            ],
            options={
                "verbose_name": "Контракт",
                "verbose_name_plural": "Контракты",
            },
        ),
        migrations.CreateModel(
            name="HistoricalContract",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("contract_number", models.CharField(db_index=True, max_length=100, verbose_name="Номер контракта")),
                ("contract_date", models.DateField(blank=True, null=True, verbose_name="Дата контракта")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_paid", "Не оплачен"),
                            ("advance_paid", "Аванс оплачен"),
                            ("intermediate", "Промежуточная оплата"),
                            ("fully_paid", "Полностью оплачен"),
                        ],
                        default="not_paid",
                        max_length=20,
                        verbose_name="Статус оплаты",
                    ),
                ),
                (
                    "advance_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name="Аванс %"),
                ),
                (
                    "intermediate_percent",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="Промежуточная оплата %"
                    ),
                ),
                (
                    "post_payment_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name="Постоплата %"),
                ),
                (
                    "amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name="Сумма"),
                ),
                ("deadline_days", models.PositiveIntegerField(blank=True, null=True, verbose_name="Срок (дней)")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
            ],
            options={
                "verbose_name": "historical Контракт",
                "verbose_name_plural": "historical Контракты",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalOrder",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("order_number", models.PositiveIntegerField(db_index=True, verbose_name="Номер заказа")),
                ("tender_number", models.CharField(blank=True, max_length=100, verbose_name="Номер тендера")),
                (
                    "status",
                    models.CharField(
                        choices=[("N", "Новый"), ("P", "В работе"), ("C", "Завершён"), ("T", "Тендер"), ("A", "Архив")],
                        db_index=True,
                        default="N",
                        max_length=1,
                        verbose_name="Статус",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Примечание")),
                ("start_date", models.DateField(blank=True, null=True, verbose_name="Дата начала")),
                ("ship_date", models.DateField(blank=True, null=True, verbose_name="Дата отгрузки")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
            ],
            options={
                "verbose_name": "historical Заказ",
                "verbose_name_plural": "historical Заказы",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order_number", models.PositiveIntegerField(unique=True, verbose_name="Номер заказа")),
                ("tender_number", models.CharField(blank=True, max_length=100, verbose_name="Номер тендера")),
                (
                    "status",
                    models.CharField(
                        choices=[("N", "Новый"), ("P", "В работе"), ("C", "Завершён"), ("T", "Тендер"), ("A", "Архив")],
                        db_index=True,
                        default="N",
                        max_length=1,
                        verbose_name="Статус",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Примечание")),
                ("start_date", models.DateField(blank=True, null=True, verbose_name="Дата начала")),
                ("ship_date", models.DateField(blank=True, null=True, verbose_name="Дата отгрузки")),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["-order_number"],
            },
        ),
        migrations.CreateModel(
            name="OrderFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="order_files/%Y/%m/", verbose_name="Файл")),
                ("original_name", models.CharField(max_length=255, verbose_name="Имя файла")),
                ("file_size", models.PositiveIntegerField(default=0, verbose_name="Размер (байт)")),
            ],
            options={
                "verbose_name": "Файл заказа",
                "verbose_name_plural": "Файлы заказов",
            },
        ),
        migrations.CreateModel(
            name="OrderOrgUnit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(blank=True, max_length=50, verbose_name="Роль")),
                ("order_index", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                ("note", models.TextField(blank=True, verbose_name="Примечание")),
            ],
            options={
                "ordering": ["order_index"],
            },
        ),
        migrations.CreateModel(
            name="OrderPQ",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_index", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
            ],
            options={
                "ordering": ["order_index"],
            },
        ),
    ]
