# Generated by Django 5.2 on 2026-02-18 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0002_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcontract',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='directory.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='customer_org_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='directory.orgunit', verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='designer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='directory.designer', verbose_name='Проектант'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='intermediary',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='directory.intermediary', verbose_name='Посредник'),
        ),
        migrations.AddField(
            model_name='order',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='orders', to='directory.contact', verbose_name='Контакты'),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='directory.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to='directory.orgunit', verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='order',
            name='designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='directory.designer', verbose_name='Проектант'),
        ),
        migrations.AddField(
            model_name='order',
            name='equipments',
            field=models.ManyToManyField(blank=True, related_name='orders', to='directory.equipment', verbose_name='Оборудование'),
        ),
        migrations.AddField(
            model_name='order',
            name='intermediary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='directory.intermediary', verbose_name='Посредник'),
        ),
        migrations.AddField(
            model_name='order',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Менеджеры'),
        ),
        migrations.AddField(
            model_name='order',
            name='related_orders',
            field=models.ManyToManyField(blank=True, to='orders.order', verbose_name='Связанные заказы'),
        ),
        migrations.AddField(
            model_name='order',
            name='works',
            field=models.ManyToManyField(blank=True, related_name='orders', to='directory.typeofwork', verbose_name='Виды работ'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='contract',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='orderfile',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='orderorgunit',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderorgunit',
            name='org_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.orgunit'),
        ),
        migrations.AddField(
            model_name='order',
            name='org_units',
            field=models.ManyToManyField(blank=True, related_name='orders', through='orders.OrderOrgUnit', to='directory.orgunit', verbose_name='Организации'),
        ),
        migrations.AddField(
            model_name='orderpq',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderpq',
            name='pq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.pq'),
        ),
        migrations.AddField(
            model_name='order',
            name='pqs',
            field=models.ManyToManyField(blank=True, related_name='orders', through='orders.OrderPQ', to='directory.pq', verbose_name='ПКЗ'),
        ),
        migrations.AlterUniqueTogether(
            name='orderorgunit',
            unique_together={('order', 'org_unit', 'role')},
        ),
    ]
