# Generated by Django 5.2 on 2026-03-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_delete_designer_remove_historicalpq_history_user_and_more'),
        ('orders', '0004_add_pg_trgm_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='facilities',
            field=models.ManyToManyField(blank=True, related_name='orders', to='directory.facility', verbose_name='Объекты'),
        ),
    ]
