# Generated by Django 5.2 on 2026-03-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_add_history_to_through_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.CharField(choices=[('N', 'Новый'), ('D', 'Договор'), ('P', 'Производство'), ('C', 'Собран'), ('S', 'Отгружен'), ('A', 'Архив')], db_index=True, default='N', max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('N', 'Новый'), ('D', 'Договор'), ('P', 'Производство'), ('C', 'Собран'), ('S', 'Отгружен'), ('A', 'Архив')], db_index=True, default='N', max_length=1, verbose_name='Статус'),
        ),
    ]
