# Generated by Django 5.2 on 2026-03-24 17:13

from django.db import migrations


def migrate_statuses(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    # T (Tender) no longer exists → convert to N (New)
    Order.objects.filter(status="T").update(status="N")


def reverse_migrate(apps, schema_editor):
    pass  # no reverse needed


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_update_order_statuses"),
    ]

    operations = [
        migrations.RunPython(migrate_statuses, reverse_migrate),
    ]
