# Generated by Django 5.2 on 2026-03-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_migrate_tender_status_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_number',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Номер контракта'),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='contract_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Номер контракта'),
        ),
    ]
