# Generated by Django 5.2 on 2026-04-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_contract_contract_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='payment_template',
            field=models.CharField(choices=[('50_50', '50% аванс, 50% перед отгрузкой'), ('100_post_7', '100% в течение 7 дней после отгрузки'), ('100_post_30', '100% в течение 30 дней после отгрузки'), ('custom', 'Произвольные условия')], default='custom', max_length=20, verbose_name='Шаблон оплаты'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='payment_template',
            field=models.CharField(choices=[('50_50', '50% аванс, 50% перед отгрузкой'), ('100_post_7', '100% в течение 7 дней после отгрузки'), ('100_post_30', '100% в течение 30 дней после отгрузки'), ('custom', 'Произвольные условия')], default='custom', max_length=20, verbose_name='Шаблон оплаты'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='order_type',
            field=models.CharField(choices=[('standard', 'Стандартный'), ('warranty', 'Гарантийный ремонт'), ('niokr', 'НИОКР'), ('replacement', 'Замена')], db_index=True, default='standard', max_length=20, verbose_name='Тип заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('standard', 'Стандартный'), ('warranty', 'Гарантийный ремонт'), ('niokr', 'НИОКР'), ('replacement', 'Замена')], db_index=True, default='standard', max_length=20, verbose_name='Тип заказа'),
        ),
    ]
