# Generated by Django 5.2 on 2026-04-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_contract_payment_template_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderfile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Файл заказа', 'verbose_name_plural': 'Файлы заказов'},
        ),
        migrations.AddField(
            model_name='orderfile',
            name='category',
            field=models.CharField(choices=[('general', 'Общий'), ('incoming', 'Входящий'), ('outgoing', 'Исходящий'), ('contract', 'Договор'), ('specification', 'Спецификация'), ('letter', 'Письмо'), ('rkd', 'РКД'), ('other', 'Другое')], db_index=True, default='general', max_length=20, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='orderfile',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Описание'),
        ),
    ]
