# Generated by Django 5.2 on 2026-04-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderfile_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('document_type', models.CharField(choices=[('contract', 'Типовой договор'), ('readiness_letter', 'Письмо о готовности'), ('overdue_letter', 'Письмо о просрочке'), ('payment_letter', 'Письмо об оплате'), ('protocol', 'Протокол разногласий'), ('other', 'Другое')], db_index=True, max_length=30, verbose_name='Тип документа')),
                ('entity', models.CharField(choices=[('npp', 'НПП Бреслер'), ('chak', 'ЧАК'), ('technopark', 'Технопарк')], db_index=True, max_length=20, verbose_name='Предприятие')),
                ('template_file', models.FileField(upload_to='document_templates/', verbose_name='Файл шаблона')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
                'ordering': ['entity', 'document_type', 'name'],
            },
        ),
    ]
