# Generated by Django 5.2 on 2026-04-06 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_document_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.PositiveIntegerField(verbose_name='Номер партии')),
                ('ship_date', models.DateField(verbose_name='Дата отгрузки')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_batches', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Партия отгрузки',
                'verbose_name_plural': 'Партии отгрузки',
                'ordering': ['batch_number'],
                'unique_together': {('order', 'batch_number')},
            },
        ),
    ]
