# Generated by Django 5.2 on 2026-03-25 05:55

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.devices.models.components


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=350, unique=True, verbose_name="Название типа компонента")),
            ],
            options={
                "verbose_name": "Тип компонента",
                "verbose_name_plural": "Типы компонентов",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DeviceRZA",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rza_name", models.CharField(max_length=350, verbose_name="Наименование устройства")),
                (
                    "rza_name_rod",
                    models.CharField(
                        blank=True, default="", max_length=350, verbose_name="Наименование в родительном падеже"
                    ),
                ),
                (
                    "rza_short_name",
                    models.CharField(blank=True, default="", max_length=250, verbose_name="Сокращённое наименование"),
                ),
                (
                    "rza_code",
                    models.CharField(max_length=350, unique=True, verbose_name="Функциональный код устройства"),
                ),
            ],
            options={
                "verbose_name": "Устройство РЗА",
                "verbose_name_plural": "Устройства РЗА",
                "ordering": ["rza_code"],
            },
        ),
        migrations.CreateModel(
            name="Parameter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=350, verbose_name="Название")),
                (
                    "parameter_type",
                    models.CharField(
                        choices=[
                            ("select", "Выбор из списка"),
                            ("custom", "Пользовательское значение"),
                            ("composite", "Составной параметр"),
                        ],
                        default="select",
                        max_length=20,
                        verbose_name="Тип параметра",
                    ),
                ),
                ("_is_leaf", models.BooleanField(db_column="is_leaf", default=True, verbose_name="Листовой элемент")),
                ("can_add_multiple", models.BooleanField(default=False, verbose_name="Можно добавлять несколько")),
                ("comment", models.TextField(blank=True, default="", verbose_name="Примечание")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
            ],
            options={
                "verbose_name": "Параметр",
                "verbose_name_plural": "Параметры",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=350, verbose_name="Наименование")),
                (
                    "internal_code",
                    models.CharField(db_index=True, max_length=120, unique=True, verbose_name="Артикул/код"),
                ),
                ("slug", models.SlugField(blank=True, max_length=350, unique=True, verbose_name="Слаг")),
                ("uom", models.CharField(default="шт", max_length=32, verbose_name="Ед. изм.")),
                (
                    "base_price",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14, verbose_name="Цена"),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("RUB", "RUB"), ("EUR", "EUR"), ("USD", "USD")],
                        default="RUB",
                        max_length=3,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("20.00"), max_digits=5, verbose_name="НДС, %"
                    ),
                ),
                ("price_with_vat", models.BooleanField(default=True, verbose_name="Цена с НДС")),
                ("track_serial", models.BooleanField(default=True, verbose_name="Требует серийный учёт")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="Активно")),
                ("is_spare_part", models.BooleanField(default=False, verbose_name="ЗИП")),
                ("valid_from", models.DateField(blank=True, null=True, verbose_name="Действует с")),
                ("valid_to", models.DateField(blank=True, null=True, verbose_name="Действует по")),
            ],
            options={
                "verbose_name": "Типовая позиция",
                "verbose_name_plural": "Типовые позиции",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100, unique=True, verbose_name="Код атрибута")),
                ("name", models.CharField(max_length=200, verbose_name="Название атрибута")),
                ("unit", models.CharField(blank=True, default="", max_length=50, verbose_name="Ед. измерения")),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("string", "Строка"),
                            ("decimal", "Число"),
                            ("bool", "Да/нет"),
                            ("choice", "Один из списка"),
                            ("multi_choice", "Несколько из списка"),
                        ],
                        default="string",
                        max_length=20,
                        verbose_name="Тип значения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Атрибут продукта",
                "verbose_name_plural": "Атрибуты продуктов",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150, verbose_name="Тип продукта")),
                ("code", models.CharField(blank=True, default="", max_length=150, verbose_name="Код типа")),
                ("mark", models.CharField(blank=True, default="", max_length=150, verbose_name="Обозначение")),
                ("description", models.TextField(blank=True, default="", verbose_name="Описание")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
            ],
            options={
                "verbose_name": "Тип продукта",
                "verbose_name_plural": "Типы продуктов",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TypicalScheme",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=350, verbose_name="Название")),
                (
                    "image",
                    models.FileField(blank=True, null=True, upload_to="typical_schemes/", verbose_name="Изображение"),
                ),
                ("description", models.TextField(blank=True, default="", verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Типовая схема",
                "verbose_name_plural": "Типовые схемы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VoltageClass",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=350, verbose_name="Классификация сетей по напряжению")),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=350, verbose_name="Название класса сети"),
                ),
            ],
            options={
                "verbose_name": "Класс напряжения",
                "verbose_name_plural": "Классы напряжения",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DeviceComponent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("produx_id", models.IntegerField(db_index=True, default=0, verbose_name="Идентификатор в БД ProdUX")),
                ("component_name", models.CharField(max_length=500, verbose_name="Наименование компонента")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("additional_data", models.JSONField(blank=True, null=True, verbose_name="Дополнительные данные")),
                (
                    "component_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="devices.componenttype",
                        verbose_name="Тип компонента",
                    ),
                ),
            ],
            options={
                "verbose_name": "Компонент терминала",
                "verbose_name_plural": "Компоненты терминалов",
                "ordering": ["component_name"],
            },
        ),
        migrations.CreateModel(
            name="ComponentVisual",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "visual_type",
                    models.CharField(
                        choices=[("rear", "Вид сзади"), ("front", "Вид спереди"), ("outline", "Габарит терминала")],
                        default="rear",
                        max_length=10,
                        verbose_name="Тип вида",
                    ),
                ),
                ("is_primary", models.BooleanField(default=False, verbose_name="Основное изображение")),
                (
                    "image_file",
                    models.ImageField(
                        upload_to=apps.devices.models.components.component_image_upload_path, verbose_name="Изображение"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(blank=True, default="", verbose_name="Описание")),
                ("image_width", models.PositiveIntegerField(blank=True, null=True, verbose_name="Ширина (px)")),
                ("image_height", models.PositiveIntegerField(blank=True, null=True, verbose_name="Высота (px)")),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visuals",
                        to="devices.devicecomponent",
                        verbose_name="Компонент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Визуальные данные компонента",
                "verbose_name_plural": "Визуальные данные компонентов",
                "ordering": ["-is_primary", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeviceRZAComponent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("price", models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Цена")),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_rza_assignments",
                        to="devices.devicecomponent",
                        verbose_name="Компонент",
                    ),
                ),
                (
                    "device_rza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_components",
                        to="devices.devicerza",
                        verbose_name="Устройство РЗА",
                    ),
                ),
            ],
            options={
                "verbose_name": "Компонент серии РЗА",
                "verbose_name_plural": "Компоненты серий РЗА",
            },
        ),
        migrations.CreateModel(
            name="ModRZA",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mod_name",
                    models.CharField(blank=True, default="", max_length=350, verbose_name="Наименование модификации"),
                ),
                ("mod_code", models.CharField(max_length=350, verbose_name="Код модификации")),
                (
                    "alter_mod_code",
                    models.CharField(
                        blank=True, default="", max_length=1000, verbose_name="Альтернативный код модификации"
                    ),
                ),
                (
                    "sec_mod_code",
                    models.CharField(blank=True, default="", max_length=500, verbose_name="Код модификации по ШЭТ"),
                ),
                (
                    "device_rza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifications",
                        to="devices.devicerza",
                        verbose_name="Устройство РЗА",
                    ),
                ),
            ],
            options={
                "verbose_name": "Модификация РЗА",
                "verbose_name_plural": "Модификации РЗА",
                "ordering": ["device_rza", "mod_code"],
            },
        ),
        migrations.CreateModel(
            name="ModRZAComponent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("price", models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Цена")),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mod_rza_assignments",
                        to="devices.devicecomponent",
                        verbose_name="Компонент",
                    ),
                ),
                (
                    "mod_rza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mod_components",
                        to="devices.modrza",
                        verbose_name="Модификация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Компонент модификации РЗА",
                "verbose_name_plural": "Компоненты модификаций РЗА",
            },
        ),
        migrations.CreateModel(
            name="ModRZAParameter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("price", models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Цена")),
                (
                    "mod_rza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mod_parameters",
                        to="devices.modrza",
                        verbose_name="Модификация",
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mod_rza_assignments",
                        to="devices.parameter",
                        verbose_name="Параметр",
                    ),
                ),
            ],
            options={
                "verbose_name": "Параметр модификации РЗА",
                "verbose_name_plural": "Параметры модификаций РЗА",
            },
        ),
        migrations.CreateModel(
            name="DeviceRZAParameter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("price", models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Цена")),
                (
                    "device_rza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_parameters",
                        to="devices.devicerza",
                        verbose_name="Устройство РЗА",
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_rza_assignments",
                        to="devices.parameter",
                        verbose_name="Параметр",
                    ),
                ),
            ],
            options={
                "verbose_name": "Параметр серии РЗА",
                "verbose_name_plural": "Параметры серий РЗА",
            },
        ),
        migrations.CreateModel(
            name="CompositeParameterTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=350, verbose_name="Название шаблона")),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="composite_templates",
                        to="devices.parameter",
                        verbose_name="Составной параметр",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаблон составного параметра",
                "verbose_name_plural": "Шаблоны составных параметров",
            },
        ),
        migrations.CreateModel(
            name="CompositeParameterField",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=350, verbose_name="Название поля")),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Текстовое поле"),
                            ("number", "Числовое поле"),
                            ("select", "Выбор из списка"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="Тип поля",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок отображения")),
                (
                    "composite_parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="composite_fields",
                        to="devices.parameter",
                        verbose_name="Составной параметр",
                    ),
                ),
                (
                    "select_parameter",
                    models.ForeignKey(
                        blank=True,
                        help_text='Только для полей типа "Выбор из списка"',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="used_in_composite_fields",
                        to="devices.parameter",
                        verbose_name="Параметр для выбора значений",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поле составного параметра",
                "verbose_name_plural": "Поля составных параметров",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ParameterValue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=350, verbose_name="Значение")),
                ("is_custom_value", models.BooleanField(default=False, verbose_name="Пользовательское значение")),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="devices.parameter",
                        verbose_name="Параметр",
                    ),
                ),
            ],
            options={
                "verbose_name": "Значение параметра",
                "verbose_name_plural": "Значения параметров",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ProductAttributeOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=100, verbose_name="Код опции")),
                ("label", models.CharField(max_length=200, verbose_name="Название опции")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="devices.productattribute",
                        verbose_name="Атрибут",
                    ),
                ),
            ],
            options={
                "verbose_name": "Опция атрибута",
                "verbose_name_plural": "Опции атрибутов",
                "ordering": ["attribute", "sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductAttributeValue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value_string", models.CharField(blank=True, max_length=500, null=True, verbose_name="Строка")),
                (
                    "value_decimal",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name="Число"),
                ),
                ("value_bool", models.BooleanField(blank=True, null=True, verbose_name="Да/нет")),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="devices.productattribute",
                        verbose_name="Атрибут",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="devices.productattributeoption",
                        verbose_name="Опция",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_values",
                        to="devices.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Значение атрибута",
                "verbose_name_plural": "Значения атрибутов",
            },
        ),
        migrations.CreateModel(
            name="ProductBOMLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("RZA_TERMINAL", "МП терминал РЗА"),
                            ("ACCESSORY", "Аксессуар/узел"),
                            ("WIRING", "Проводка/шкафной монтаж"),
                            ("MISC", "Прочее"),
                        ],
                        default="MISC",
                        max_length=32,
                        verbose_name="Роль",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1, verbose_name="Количество")),
                ("slot_label", models.CharField(blank=True, default="", max_length=120, verbose_name="Слот/место")),
                (
                    "track_serial_override",
                    models.BooleanField(blank=True, null=True, verbose_name="Серийный учёт (override)"),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="used_in_boms",
                        to="devices.product",
                        verbose_name="Компонент",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_lines",
                        to="devices.product",
                        verbose_name="Родитель (сборка)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка состава изделия",
                "verbose_name_plural": "Состав изделия (BOM)",
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=350, verbose_name="Название")),
                (
                    "short_name",
                    models.CharField(blank=True, default="", max_length=150, verbose_name="Сокращённое название"),
                ),
                ("slug", models.SlugField(blank=True, max_length=350, unique=True, verbose_name="Слаг")),
                ("description", models.TextField(blank=True, default="", verbose_name="Описание")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
            ],
            options={
                "verbose_name": "Категория каталога",
                "verbose_name_plural": "Категории каталога",
                "indexes": [models.Index(fields=["is_active"], name="devices_pro_is_acti_d35f64_idx")],
            },
        ),
        migrations.CreateModel(
            name="CatalogPlacement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalog_placements",
                        to="devices.product",
                        verbose_name="Типовая позиция",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_placements",
                        to="devices.productcategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Размещение в каталоге",
                "verbose_name_plural": "Размещения в каталоге",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="devices.producttype",
                verbose_name="Тип продукта",
            ),
        ),
        migrations.CreateModel(
            name="RZASpec",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True, default="", verbose_name="Описание")),
                (
                    "device_rza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rza_specs",
                        to="devices.devicerza",
                        verbose_name="Функциональный код",
                    ),
                ),
                (
                    "mod_rza",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rza_specs",
                        to="devices.modrza",
                        verbose_name="Модификация",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rza_spec",
                        to="devices.product",
                        verbose_name="Типовая позиция",
                    ),
                ),
            ],
            options={
                "verbose_name": "Спецификация РЗА",
                "verbose_name_plural": "Спецификации РЗА",
            },
        ),
        migrations.CreateModel(
            name="TerminalLayout",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("layout_data", models.JSONField(default=dict, verbose_name="Данные расстановки")),
                ("is_auto_generated", models.BooleanField(default=True, verbose_name="Автоматически сгенерирована")),
                (
                    "mod_rza",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layout",
                        to="devices.modrza",
                        verbose_name="Модификация",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расстановка компонентов",
                "verbose_name_plural": "Расстановки компонентов",
            },
        ),
        migrations.AddIndex(
            model_name="devicecomponent",
            index=models.Index(fields=["component_type", "is_active"], name="idx_component_type_active"),
        ),
        migrations.AddConstraint(
            model_name="componentvisual",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("component", "visual_type", "is_primary"),
                name="unique_primary_visual_per_type",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="devicerzacomponent",
            unique_together={("device_rza", "component")},
        ),
        migrations.AddConstraint(
            model_name="modrza",
            constraint=models.UniqueConstraint(fields=("device_rza", "mod_code"), name="unique_mod_code_per_device"),
        ),
        migrations.AlterUniqueTogether(
            name="modrzacomponent",
            unique_together={("mod_rza", "component")},
        ),
        migrations.AlterUniqueTogether(
            name="modrzaparameter",
            unique_together={("mod_rza", "parameter")},
        ),
        migrations.AlterUniqueTogether(
            name="devicerzaparameter",
            unique_together={("device_rza", "parameter")},
        ),
        migrations.AlterUniqueTogether(
            name="productattributeoption",
            unique_together={("attribute", "code")},
        ),
        migrations.AddIndex(
            model_name="productattributevalue",
            index=models.Index(fields=["product"], name="devices_pro_product_dcb98e_idx"),
        ),
        migrations.AddIndex(
            model_name="productattributevalue",
            index=models.Index(fields=["attribute"], name="devices_pro_attribu_c87a18_idx"),
        ),
        migrations.AddIndex(
            model_name="productbomline",
            index=models.Index(fields=["parent"], name="devices_pro_parent__8288e4_idx"),
        ),
        migrations.AddIndex(
            model_name="productbomline",
            index=models.Index(fields=["child"], name="devices_pro_child_i_155dec_idx"),
        ),
        migrations.AddConstraint(
            model_name="productbomline",
            constraint=models.UniqueConstraint(
                fields=("parent", "child", "slot_label"), name="unique_bom_parent_child_slot"
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogplacement",
            constraint=models.UniqueConstraint(fields=("product", "category"), name="unique_product_category"),
        ),
    ]
