# Generated by Django 5.2 on 2026-04-02 18:36

from decimal import Decimal

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalDeviceComponent",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("produx_id", models.IntegerField(db_index=True, default=0, verbose_name="Идентификатор в БД ProdUX")),
                ("component_name", models.CharField(max_length=500, verbose_name="Наименование компонента")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("additional_data", models.JSONField(blank=True, null=True, verbose_name="Дополнительные данные")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "component_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="devices.componenttype",
                        verbose_name="Тип компонента",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Компонент терминала",
                "verbose_name_plural": "historical Компоненты терминалов",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDeviceRZA",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("rza_name", models.CharField(max_length=350, verbose_name="Наименование устройства")),
                (
                    "rza_name_rod",
                    models.CharField(
                        blank=True, default="", max_length=350, verbose_name="Наименование в родительном падеже"
                    ),
                ),
                (
                    "rza_short_name",
                    models.CharField(blank=True, default="", max_length=250, verbose_name="Сокращённое наименование"),
                ),
                (
                    "rza_code",
                    models.CharField(db_index=True, max_length=350, verbose_name="Функциональный код устройства"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Устройство РЗА",
                "verbose_name_plural": "historical Устройства РЗА",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalModRZA",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "mod_name",
                    models.CharField(blank=True, default="", max_length=350, verbose_name="Наименование модификации"),
                ),
                ("mod_code", models.CharField(max_length=350, verbose_name="Код модификации")),
                (
                    "alter_mod_code",
                    models.CharField(
                        blank=True, default="", max_length=1000, verbose_name="Альтернативный код модификации"
                    ),
                ),
                (
                    "sec_mod_code",
                    models.CharField(blank=True, default="", max_length=500, verbose_name="Код модификации по ШЭТ"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "device_rza",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="devices.devicerza",
                        verbose_name="Устройство РЗА",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Модификация РЗА",
                "verbose_name_plural": "historical Модификации РЗА",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProduct",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("name", models.CharField(max_length=350, verbose_name="Наименование")),
                ("internal_code", models.CharField(db_index=True, max_length=120, verbose_name="Артикул/код")),
                ("slug", models.SlugField(blank=True, max_length=350, verbose_name="Слаг")),
                ("uom", models.CharField(default="шт", max_length=32, verbose_name="Ед. изм.")),
                (
                    "base_price",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14, verbose_name="Цена"),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("RUB", "RUB"), ("EUR", "EUR"), ("USD", "USD")],
                        default="RUB",
                        max_length=3,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("20.00"), max_digits=5, verbose_name="НДС, %"
                    ),
                ),
                ("price_with_vat", models.BooleanField(default=True, verbose_name="Цена с НДС")),
                ("track_serial", models.BooleanField(default=True, verbose_name="Требует серийный учёт")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="Активно")),
                ("is_spare_part", models.BooleanField(default=False, verbose_name="ЗИП")),
                ("valid_from", models.DateField(blank=True, null=True, verbose_name="Действует с")),
                ("valid_to", models.DateField(blank=True, null=True, verbose_name="Действует по")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="devices.producttype",
                        verbose_name="Тип продукта",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Типовая позиция",
                "verbose_name_plural": "historical Типовые позиции",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
