# Generated by Django 5.2 on 2026-04-08 16:31

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_historicaldevicecomponent_historicaldevicerza_and_more'),
        ('directory', '0005_historicalcity_historicalcontact_historicalcountry_and_more'),
        ('orders', '0014_shipment_batch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('ordered', 'Заказано'), ('partial', 'Частичная поставка'), ('delivered', 'Доставлено'), ('cancelled', 'Отменено')], default='draft', max_length=20, verbose_name='Статус')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Дата заказа')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Ожидаемая дата поставки')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='orders.order', verbose_name='Заказ')),
                ('purchaser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='Закупщик')),
                ('supplier', models.ForeignKey(limit_choices_to={'business_role': 'supplier'}, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='directory.orgunit', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Закупочный ордер',
                'verbose_name_plural': 'Закупочные ордера',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='purchasing/files/%Y/%m/', verbose_name='Файл')),
                ('original_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Размер (байт)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='purchasing.purchaseorder', verbose_name='Закупочный ордер')),
            ],
            options={
                'verbose_name': 'Файл закупки',
                'verbose_name_plural': 'Файлы закупки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Цена за ед.')),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Итого')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Срок поставки')),
                ('delivered_quantity', models.PositiveIntegerField(default=0, verbose_name='Поставлено')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_lines', to='devices.product', verbose_name='Продукт')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchaseorder', verbose_name='Закупочный ордер')),
            ],
            options={
                'verbose_name': 'Позиция закупки',
                'verbose_name_plural': 'Позиции закупки',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Сумма')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('due_date', models.DateField(blank=True, help_text='Для постоплаты — дата, к которой нужно оплатить', null=True, verbose_name='Срок оплаты')),
                ('status', models.CharField(choices=[('pending_approval', 'На согласовании'), ('approved', 'Согласовано'), ('paid', 'Оплачено'), ('rejected', 'Отклонено')], default='pending_approval', max_length=20, verbose_name='Статус')),
                ('invoice_file', models.FileField(blank=True, upload_to='purchasing/invoices/%Y/%m/', verbose_name='Счёт')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Номер счёта')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to=settings.AUTH_USER_MODEL, verbose_name='Согласовал')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='purchasing.purchaseorder', verbose_name='Закупочный ордер')),
            ],
            options={
                'verbose_name': 'Оплата закупки',
                'verbose_name_plural': 'Оплаты закупок',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Подана'), ('in_progress', 'В работе'), ('completed', 'Выполнена'), ('cancelled', 'Отменена')], default='draft', max_length=20, verbose_name='Статус')),
                ('required_date', models.DateField(blank=True, null=True, verbose_name='Требуемая дата')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Заявка на закупку',
                'verbose_name_plural': 'Заявки на закупку',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='purchasing.purchaserequest', verbose_name='Заявка на закупку'),
        ),
        migrations.CreateModel(
            name='HistoricalPurchaseOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('ordered', 'Заказано'), ('partial', 'Частичная поставка'), ('delivered', 'Доставлено'), ('cancelled', 'Отменено')], default='draft', max_length=20, verbose_name='Статус')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Дата заказа')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Ожидаемая дата поставки')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.order', verbose_name='Заказ')),
                ('purchaser', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Закупщик')),
                ('supplier', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'business_role': 'supplier'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='directory.orgunit', verbose_name='Поставщик')),
                ('purchase_request', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchasing.purchaserequest', verbose_name='Заявка на закупку')),
            ],
            options={
                'verbose_name': 'historical Закупочный ордер',
                'verbose_name_plural': 'historical Закупочные ордера',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PurchaseRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('target_description', models.CharField(blank=True, help_text='Шкаф, дверца, заводской номер и т.д.', max_length=500, verbose_name='Назначение')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_request_lines', to='devices.product', verbose_name='Продукт')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchaserequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Позиция заявки',
                'verbose_name_plural': 'Позиции заявки',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('reserved', models.PositiveIntegerField(default=0, verbose_name='Зарезервировано')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_item', to='devices.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Позиция на складе',
                'verbose_name_plural': 'Позиции на складе',
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('receipt', 'Приход'), ('issue', 'Расход'), ('reserve', 'Резервирование'), ('unreserve', 'Снятие резерва')], max_length=20, verbose_name='Тип движения')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='orders.order', verbose_name='Заказ')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='purchasing.stockitem', verbose_name='Позиция')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Движение по складу',
                'verbose_name_plural': 'Движения по складу',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Скидка (%)')),
                ('payment_terms', models.CharField(blank=True, max_length=500, verbose_name='Условия оплаты')),
                ('delivery_terms', models.CharField(blank=True, max_length=500, verbose_name='Условия доставки')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('supplier', models.OneToOneField(limit_choices_to={'business_role': 'supplier'}, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_conditions', to='directory.orgunit', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Условия поставщика',
                'verbose_name_plural': 'Условия поставщиков',
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='orders.order', verbose_name='Заказ')),
                ('reserved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Кто забронировал')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='purchasing.stockitem', verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
                'unique_together': {('stock_item', 'order')},
            },
        ),
    ]
