# Generated by Django 5.2 on 2026-04-21 14:51

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models

import apps.edo.internal_docs.models.document


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0003_documentlink"),
        ("directory", "0010_add_department_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalChainTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "steps",
                    models.JSONField(
                        default=list,
                        help_text='Список шагов: [{"order": 1, "role_key": "supervisor", "label": "...", "action": "approve", "sla_hours": 24, "parallel_group": null}, ...]. Формат и доступные role_key — см. ТЗ §3.4 + §15.0.',
                        verbose_name="Шаги",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Информационно; реальная привязка — через DocumentType.default_chain",
                        verbose_name="Дефолтная",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Цепочка согласования",
                "verbose_name_plural": "Цепочки согласования",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InternalDocFlowConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "cross_company_scope",
                    models.CharField(
                        choices=[("company_only", "Только своя компания"), ("group_wide", "Вся группа компаний")],
                        default="company_only",
                        help_text="company_only: сотрудники компании A не видят документы компании B; group_wide: публичные документы видны всей группе компаний",
                        max_length=20,
                        verbose_name="Режим межкомпанийной видимости",
                    ),
                ),
                (
                    "default_sla_hours",
                    models.PositiveIntegerField(
                        default=48,
                        help_text="Используется, если в шаге цепочки не задан sla_hours",
                        verbose_name="SLA по умолчанию (часы)",
                    ),
                ),
                (
                    "pdf_cache_ttl_hours",
                    models.PositiveIntegerField(
                        default=168,
                        help_text="Сколько времени хранить сгенерированный PDF на диске",
                        verbose_name="TTL кеша PDF (часы)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Конфиг ЭДО",
                "verbose_name_plural": "Конфиг ЭДО",
            },
        ),
        migrations.CreateModel(
            name="ApprovalStep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveSmallIntegerField(verbose_name="Порядок")),
                (
                    "parallel_group",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Одинаковое значение → шаги идут параллельно",
                        max_length=50,
                        verbose_name="Параллельная группа",
                    ),
                ),
                (
                    "role_key",
                    models.CharField(
                        help_text="supervisor / dept_head:parent / group:accounting@company / fixed_user:42 / ...",
                        max_length=100,
                        verbose_name="Ключ роли",
                    ),
                ),
                ("role_label", models.CharField(max_length=255, verbose_name="Отображаемое название роли")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approve", "Согласовать"),
                            ("sign", "Подписать"),
                            ("notify_only", "Только уведомить"),
                            ("inform", "Ознакомить"),
                        ],
                        default="approve",
                        max_length=20,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("approved", "Согласовано"),
                            ("rejected", "Отклонено"),
                            ("revision_requested", "Запрошены правки"),
                            ("skipped", "Пропущен"),
                            ("delegated", "Делегирован"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "signature_image",
                    models.TextField(
                        blank=True,
                        help_text="Опционально, если DocumentType.requires_drawn_signature=True",
                        verbose_name="Рисованная подпись (data-URL)",
                    ),
                ),
                ("sla_due_at", models.DateTimeField(blank=True, null=True, verbose_name="SLA истекает")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        help_text="Резолвится при submit",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_steps",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Согласующий",
                    ),
                ),
                (
                    "original_approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Изначальный согласующий (до делегирования)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаг согласования",
                "verbose_name_plural": "Шаги согласования",
                "ordering": ["document", "order"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Присваивается при submit (draft → pending)",
                        max_length=50,
                        verbose_name="Номер",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=500, verbose_name="Заголовок")),
                (
                    "field_values",
                    models.JSONField(
                        default=dict, help_text="По схеме DocumentType.field_schema", verbose_name="Значения полей"
                    ),
                ),
                (
                    "body_rendered",
                    models.TextField(
                        blank=True,
                        help_text="Результат прогона body_template на момент submit; не меняется задним числом",
                        verbose_name="Отрендеренное тело",
                    ),
                ),
                (
                    "header_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"company_name": "...", "head_name": "...", "head_position": "..."}',
                        verbose_name="Снепшот шапки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("pending", "На согласовании"),
                            ("approved", "Согласовано"),
                            ("rejected", "Отклонено"),
                            ("revision_requested", "Запрошены правки"),
                            ("cancelled", "Отменено"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "chain_snapshot",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Копия ApprovalChainTemplate.steps на момент submit",
                        verbose_name="Снепшот цепочки",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "addressee",
                    models.ForeignKey(
                        blank=True,
                        help_text="Для уведомлений и адресных заявлений",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_internal_docs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Адресат (опционально)",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authored_internal_docs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "author_company_unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Фиксируется на момент submit для multi-tenant фильтрации",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authored_internal_docs",
                        to="directory.orgunit",
                        verbose_name="Компания автора (снепшот)",
                    ),
                ),
                (
                    "author_department_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_internal_docs",
                        to="directory.department",
                        verbose_name="Подразделение автора (снепшот)",
                    ),
                ),
                (
                    "current_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="internal_docs.approvalstep",
                        verbose_name="Текущий шаг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ",
                "verbose_name_plural": "Документы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="approvalstep",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="internal_docs.document",
                verbose_name="Документ",
            ),
        ),
        migrations.CreateModel(
            name="DocumentAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.edo.internal_docs.models.document._attachment_upload_path, verbose_name="Файл"
                    ),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="Имя файла")),
                ("file_size", models.PositiveIntegerField(default=0, verbose_name="Размер (байт)")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="internal_docs.document",
                        verbose_name="Документ",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachments",
                        to="internal_docs.approvalstep",
                        verbose_name="Шаг (если файл прикреплён в рамках шага)",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_internal_doc_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Загрузил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вложение документа",
                "verbose_name_plural": "Вложения документов",
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "code",
                    models.SlugField(
                        help_text="Slug: memo_free, memo_overtime, vacation_notification, ...",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Код",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("memo", "Служебные записки"),
                            ("application", "Заявления"),
                            ("notification", "Уведомления"),
                            ("travel", "Командировки"),
                            ("bonus", "Премирование"),
                            ("other", "Другое"),
                        ],
                        default="memo",
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Имя lucide-иконки для UI (file-text, clock-alert, mail, ...)",
                        max_length=50,
                        verbose_name="Иконка",
                    ),
                ),
                (
                    "field_schema",
                    models.JSONField(
                        default=list, help_text="Список полей формы; см. ТЗ §4.2 + §15.0", verbose_name="Схема полей"
                    ),
                ),
                (
                    "body_template",
                    models.TextField(
                        blank=True,
                        help_text="Django Template Language. Доступны: author, today, document, fields + поля по имени.",
                        verbose_name="Шаблон тела",
                    ),
                ),
                (
                    "title_template",
                    models.CharField(
                        blank=True,
                        help_text="Например: Служебная записка «{{ subject }}»",
                        max_length=500,
                        verbose_name="Шаблон заголовка",
                    ),
                ),
                (
                    "requires_drawn_signature",
                    models.BooleanField(
                        default=False,
                        help_text="Для командировочных смет и уведомлений об отпуске",
                        verbose_name="Требует рисованную подпись",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("personal_only", "Только автор и согласующие"),
                            ("department_visible", "Виден сотрудникам подразделения"),
                            ("public", "Виден всем (в рамках tenant-скоупа)"),
                        ],
                        default="personal_only",
                        max_length=30,
                        verbose_name="Видимость",
                    ),
                ),
                (
                    "tenancy_override",
                    models.CharField(
                        blank=True,
                        choices=[("group_wide", "Вся группа компаний"), ("company_only", "Только своя компания")],
                        default="",
                        help_text="Пусто = использовать глобальный InternalDocFlowConfig.cross_company_scope",
                        max_length=20,
                        verbose_name="Межкомпанийная видимость (override)",
                    ),
                ),
                (
                    "initiator_resolver",
                    models.CharField(
                        choices=[
                            ("author", "Любой сотрудник"),
                            ("group:accounting", "Бухгалтерия"),
                            ("group:hr", "HR / Отдел кадров"),
                            ("group:admin", "Администраторы"),
                        ],
                        default="author",
                        max_length=30,
                        verbose_name="Кто может создавать",
                    ),
                ),
                (
                    "addressee_mode",
                    models.CharField(
                        choices=[
                            ("none", "Нет адресата"),
                            ("single_user", "Конкретный сотрудник"),
                            ("dept_head", "Руководитель подразделения"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="Режим адресата",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="default_for_types",
                        to="internal_docs.approvalchaintemplate",
                        verbose_name="Дефолтная цепочка согласования",
                    ),
                ),
                (
                    "numbering_sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_types",
                        to="core.numbersequence",
                        verbose_name="Нумерация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип документа",
                "verbose_name_plural": "Типы документов",
                "ordering": ["category", "name"],
            },
        ),
        migrations.AddField(
            model_name="document",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="internal_docs.documenttype",
                verbose_name="Тип документа",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalApprovalChainTemplate",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "steps",
                    models.JSONField(
                        default=list,
                        help_text='Список шагов: [{"order": 1, "role_key": "supervisor", "label": "...", "action": "approve", "sla_hours": 24, "parallel_group": null}, ...]. Формат и доступные role_key — см. ТЗ §3.4 + §15.0.',
                        verbose_name="Шаги",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Информационно; реальная привязка — через DocumentType.default_chain",
                        verbose_name="Дефолтная",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Цепочка согласования",
                "verbose_name_plural": "historical Цепочки согласования",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalApprovalStep",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("order", models.PositiveSmallIntegerField(verbose_name="Порядок")),
                (
                    "parallel_group",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Одинаковое значение → шаги идут параллельно",
                        max_length=50,
                        verbose_name="Параллельная группа",
                    ),
                ),
                (
                    "role_key",
                    models.CharField(
                        help_text="supervisor / dept_head:parent / group:accounting@company / fixed_user:42 / ...",
                        max_length=100,
                        verbose_name="Ключ роли",
                    ),
                ),
                ("role_label", models.CharField(max_length=255, verbose_name="Отображаемое название роли")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approve", "Согласовать"),
                            ("sign", "Подписать"),
                            ("notify_only", "Только уведомить"),
                            ("inform", "Ознакомить"),
                        ],
                        default="approve",
                        max_length=20,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("approved", "Согласовано"),
                            ("rejected", "Отклонено"),
                            ("revision_requested", "Запрошены правки"),
                            ("skipped", "Пропущен"),
                            ("delegated", "Делегирован"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                ("sla_due_at", models.DateTimeField(blank=True, null=True, verbose_name="SLA истекает")),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Резолвится при submit",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Согласующий",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="internal_docs.document",
                        verbose_name="Документ",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "original_approver",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Изначальный согласующий (до делегирования)",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Шаг согласования",
                "verbose_name_plural": "historical Шаги согласования",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDocument",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Присваивается при submit (draft → pending)",
                        max_length=50,
                        verbose_name="Номер",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=500, verbose_name="Заголовок")),
                (
                    "field_values",
                    models.JSONField(
                        default=dict, help_text="По схеме DocumentType.field_schema", verbose_name="Значения полей"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("pending", "На согласовании"),
                            ("approved", "Согласовано"),
                            ("rejected", "Отклонено"),
                            ("revision_requested", "Запрошены правки"),
                            ("cancelled", "Отменено"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "addressee",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Для уведомлений и адресных заявлений",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Адресат (опционально)",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "author_company_unit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Фиксируется на момент submit для multi-tenant фильтрации",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="directory.orgunit",
                        verbose_name="Компания автора (снепшот)",
                    ),
                ),
                (
                    "author_department_unit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="directory.department",
                        verbose_name="Подразделение автора (снепшот)",
                    ),
                ),
                (
                    "current_step",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="internal_docs.approvalstep",
                        verbose_name="Текущий шаг",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="internal_docs.documenttype",
                        verbose_name="Тип документа",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Документ",
                "verbose_name_plural": "historical Документы",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDocumentType",
            fields=[
                (
                    "code",
                    models.SlugField(
                        help_text="Slug: memo_free, memo_overtime, vacation_notification, ...", verbose_name="Код"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("memo", "Служебные записки"),
                            ("application", "Заявления"),
                            ("notification", "Уведомления"),
                            ("travel", "Командировки"),
                            ("bonus", "Премирование"),
                            ("other", "Другое"),
                        ],
                        default="memo",
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Имя lucide-иконки для UI (file-text, clock-alert, mail, ...)",
                        max_length=50,
                        verbose_name="Иконка",
                    ),
                ),
                (
                    "field_schema",
                    models.JSONField(
                        default=list, help_text="Список полей формы; см. ТЗ §4.2 + §15.0", verbose_name="Схема полей"
                    ),
                ),
                (
                    "body_template",
                    models.TextField(
                        blank=True,
                        help_text="Django Template Language. Доступны: author, today, document, fields + поля по имени.",
                        verbose_name="Шаблон тела",
                    ),
                ),
                (
                    "title_template",
                    models.CharField(
                        blank=True,
                        help_text="Например: Служебная записка «{{ subject }}»",
                        max_length=500,
                        verbose_name="Шаблон заголовка",
                    ),
                ),
                (
                    "requires_drawn_signature",
                    models.BooleanField(
                        default=False,
                        help_text="Для командировочных смет и уведомлений об отпуске",
                        verbose_name="Требует рисованную подпись",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("personal_only", "Только автор и согласующие"),
                            ("department_visible", "Виден сотрудникам подразделения"),
                            ("public", "Виден всем (в рамках tenant-скоупа)"),
                        ],
                        default="personal_only",
                        max_length=30,
                        verbose_name="Видимость",
                    ),
                ),
                (
                    "tenancy_override",
                    models.CharField(
                        blank=True,
                        choices=[("group_wide", "Вся группа компаний"), ("company_only", "Только своя компания")],
                        default="",
                        help_text="Пусто = использовать глобальный InternalDocFlowConfig.cross_company_scope",
                        max_length=20,
                        verbose_name="Межкомпанийная видимость (override)",
                    ),
                ),
                (
                    "initiator_resolver",
                    models.CharField(
                        choices=[
                            ("author", "Любой сотрудник"),
                            ("group:accounting", "Бухгалтерия"),
                            ("group:hr", "HR / Отдел кадров"),
                            ("group:admin", "Администраторы"),
                        ],
                        default="author",
                        max_length=30,
                        verbose_name="Кто может создавать",
                    ),
                ),
                (
                    "addressee_mode",
                    models.CharField(
                        choices=[
                            ("none", "Нет адресата"),
                            ("single_user", "Конкретный сотрудник"),
                            ("dept_head", "Руководитель подразделения"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="Режим адресата",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "default_chain",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="internal_docs.approvalchaintemplate",
                        verbose_name="Дефолтная цепочка согласования",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "numbering_sequence",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.numbersequence",
                        verbose_name="Нумерация",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Тип документа",
                "verbose_name_plural": "historical Типы документов",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name="approvalstep",
            index=models.Index(fields=["approver", "status"], name="internal_do_approve_19b256_idx"),
        ),
        migrations.AddIndex(
            model_name="approvalstep",
            index=models.Index(fields=["document", "order"], name="internal_do_documen_06c4db_idx"),
        ),
        migrations.AddConstraint(
            model_name="approvalstep",
            constraint=models.UniqueConstraint(
                fields=("document", "order", "parallel_group"), name="uniq_step_per_document_order_group"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["author", "status"], name="internal_do_author__714821_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["type", "status"], name="internal_do_type_id_ab5cf0_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["-submitted_at"], name="internal_do_submitt_4018cc_idx"),
        ),
    ]
