# Generated by Django 5.2 on 2026-04-26 09:33

from django.db import migrations, models

import apps.edo.internal_docs.services.schema


class Migration(migrations.Migration):
    dependencies = [
        ("internal_docs", "0006_memo_overtime_subtree_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documenttype",
            name="field_schema",
            field=models.JSONField(
                default=list,
                help_text="Список полей формы; см. ТЗ §4.2 + §15.0",
                validators=[apps.edo.internal_docs.services.schema.validate_field_schema],
                verbose_name="Схема полей",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldocumenttype",
            name="field_schema",
            field=models.JSONField(
                default=list,
                help_text="Список полей формы; см. ТЗ §4.2 + §15.0",
                validators=[apps.edo.internal_docs.services.schema.validate_field_schema],
                verbose_name="Схема полей",
            ),
        ),
    ]
