# Generated by Django 5.2 on 2026-04-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("internal_docs", "0007_alter_documenttype_field_schema_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalstep",
            name="parallel_mode",
            field=models.CharField(
                choices=[("and", "Все участники (AND)"), ("or", "Любой участник (OR)")],
                default="and",
                help_text="AND — все должны согласовать; OR — достаточно одного",
                max_length=10,
                verbose_name="Режим параллельного согласования",
            ),
        ),
        migrations.AddField(
            model_name="historicalapprovalstep",
            name="parallel_mode",
            field=models.CharField(
                choices=[("and", "Все участники (AND)"), ("or", "Любой участник (OR)")],
                default="and",
                help_text="AND — все должны согласовать; OR — достаточно одного",
                max_length=10,
                verbose_name="Режим параллельного согласования",
            ),
        ),
        migrations.AlterField(
            model_name="approvalstep",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Ожидает активации"),
                    ("pending", "Ожидает решения"),
                    ("approved", "Согласовано"),
                    ("rejected", "Отклонено"),
                    ("revision_requested", "Запрошены правки"),
                    ("skipped", "Пропущен"),
                    ("delegated", "Делегирован"),
                ],
                db_index=True,
                default="pending",
                max_length=30,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="historicalapprovalstep",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Ожидает активации"),
                    ("pending", "Ожидает решения"),
                    ("approved", "Согласовано"),
                    ("rejected", "Отклонено"),
                    ("revision_requested", "Запрошены правки"),
                    ("skipped", "Пропущен"),
                    ("delegated", "Делегирован"),
                ],
                db_index=True,
                default="pending",
                max_length=30,
                verbose_name="Статус",
            ),
        ),
    ]
