# Generated by Django 5.2 on 2026-04-30 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0012_orgunithead'),
        ('internal_docs', '0011_approvalstep_internal_do_status_44cad0_idx_and_more'),
        ('users', '0012_remove_user_company_remove_user_company_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='author_assignment',
            field=models.ForeignKey(blank=True, help_text='Контекст подачи документа: с какой штатной позиции (компания+отдел+должность) автор подал документ. Влияет на резолв chain (dept_head, company_head и т.д.). Фиксируется на submit; если запись помечена is_active=False, документ не теряется.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authored_internal_docs', to='users.assignment', verbose_name='Штатное назначение автора'),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='author_assignment',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Контекст подачи документа: с какой штатной позиции (компания+отдел+должность) автор подал документ. Влияет на резолв chain (dept_head, company_head и т.д.). Фиксируется на submit; если запись помечена is_active=False, документ не теряется.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.assignment', verbose_name='Штатное назначение автора'),
        ),
        migrations.AlterField(
            model_name='document',
            name='author_company_unit',
            field=models.ForeignKey(blank=True, help_text='Денормализация author_assignment.company для индексов видимости', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authored_internal_docs', to='directory.orgunit', verbose_name='Компания автора (снепшот)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='author_department_unit',
            field=models.ForeignKey(blank=True, help_text='Денормализация author_assignment.department для индексов видимости', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_internal_docs', to='directory.department', verbose_name='Подразделение автора (снепшот)'),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='author_company_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Денормализация author_assignment.company для индексов видимости', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='directory.orgunit', verbose_name='Компания автора (снепшот)'),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='author_department_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Денормализация author_assignment.department для индексов видимости', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='directory.department', verbose_name='Подразделение автора (снепшот)'),
        ),
    ]
